// Code generated by protoc-gen-go.
// source: proto/registrar.proto
// DO NOT EDIT!

/*
Package registrar is a generated protocol buffer package.

It is generated from these files:
	proto/registrar.proto

It has these top-level messages:
	ServiceDescription
	ServiceAddress
	ServiceLocation
	GetRequest
	GetResponse
	ShutdownRequest
	ListResponse
	EmptyResponse
	ListRequest
	DeregisterRequest
*/
package registrar

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServiceDescription_Servicetype int32

const (
	ServiceDescription_grpc ServiceDescription_Servicetype = 0
	ServiceDescription_json ServiceDescription_Servicetype = 1
)

var ServiceDescription_Servicetype_name = map[int32]string{
	0: "grpc",
	1: "json",
}
var ServiceDescription_Servicetype_value = map[string]int32{
	"grpc": 0,
	"json": 1,
}

func (x ServiceDescription_Servicetype) String() string {
	return proto.EnumName(ServiceDescription_Servicetype_name, int32(x))
}
func (ServiceDescription_Servicetype) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

type ServiceDescription struct {
	Name  string                         `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
	Build int64                          `protobuf:"varint,2,opt,name=Build,json=build" json:"Build,omitempty"`
	Type  ServiceDescription_Servicetype `protobuf:"varint,4,opt,name=type,enum=registrar.ServiceDescription_Servicetype" json:"type,omitempty"`
}

func (m *ServiceDescription) Reset()                    { *m = ServiceDescription{} }
func (m *ServiceDescription) String() string            { return proto.CompactTextString(m) }
func (*ServiceDescription) ProtoMessage()               {}
func (*ServiceDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServiceDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ServiceDescription) GetBuild() int64 {
	if m != nil {
		return m.Build
	}
	return 0
}

func (m *ServiceDescription) GetType() ServiceDescription_Servicetype {
	if m != nil {
		return m.Type
	}
	return ServiceDescription_grpc
}

type ServiceAddress struct {
	Host string `protobuf:"bytes,1,opt,name=Host,json=host" json:"Host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=Port,json=port" json:"Port,omitempty"`
}

func (m *ServiceAddress) Reset()                    { *m = ServiceAddress{} }
func (m *ServiceAddress) String() string            { return proto.CompactTextString(m) }
func (*ServiceAddress) ProtoMessage()               {}
func (*ServiceAddress) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServiceAddress) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ServiceAddress) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ServiceLocation struct {
	Service *ServiceDescription `protobuf:"bytes,1,opt,name=Service,json=service" json:"Service,omitempty"`
	Address []*ServiceAddress   `protobuf:"bytes,2,rep,name=Address,json=address" json:"Address,omitempty"`
}

func (m *ServiceLocation) Reset()                    { *m = ServiceLocation{} }
func (m *ServiceLocation) String() string            { return proto.CompactTextString(m) }
func (*ServiceLocation) ProtoMessage()               {}
func (*ServiceLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ServiceLocation) GetService() *ServiceDescription {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *ServiceLocation) GetAddress() []*ServiceAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

type GetRequest struct {
	Service *ServiceDescription `protobuf:"bytes,1,opt,name=Service,json=service" json:"Service,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRequest) GetService() *ServiceDescription {
	if m != nil {
		return m.Service
	}
	return nil
}

type GetResponse struct {
	Service   *ServiceDescription `protobuf:"bytes,1,opt,name=Service,json=service" json:"Service,omitempty"`
	Location  *ServiceLocation    `protobuf:"bytes,2,opt,name=Location,json=location" json:"Location,omitempty"`
	ServiceID string              `protobuf:"bytes,3,opt,name=ServiceID,json=serviceID" json:"ServiceID,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetResponse) GetService() *ServiceDescription {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *GetResponse) GetLocation() *ServiceLocation {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *GetResponse) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

type ShutdownRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=ServiceName,json=serviceName" json:"ServiceName,omitempty"`
}

func (m *ShutdownRequest) Reset()                    { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string            { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()               {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ShutdownRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type ListResponse struct {
	Service []*GetResponse `protobuf:"bytes,3,rep,name=Service,json=service" json:"Service,omitempty"`
}

func (m *ListResponse) Reset()                    { *m = ListResponse{} }
func (m *ListResponse) String() string            { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()               {}
func (*ListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListResponse) GetService() []*GetResponse {
	if m != nil {
		return m.Service
	}
	return nil
}

type EmptyResponse struct {
}

func (m *EmptyResponse) Reset()                    { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string            { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()               {}
func (*EmptyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ListRequest struct {
	// optional - if set filter by Name
	Name string `protobuf:"bytes,1,opt,name=Name,json=name" json:"Name,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ListRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeregisterRequest struct {
	ServiceID string `protobuf:"bytes,1,opt,name=ServiceID,json=serviceID" json:"ServiceID,omitempty"`
}

func (m *DeregisterRequest) Reset()                    { *m = DeregisterRequest{} }
func (m *DeregisterRequest) String() string            { return proto.CompactTextString(m) }
func (*DeregisterRequest) ProtoMessage()               {}
func (*DeregisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeregisterRequest) GetServiceID() string {
	if m != nil {
		return m.ServiceID
	}
	return ""
}

func init() {
	proto.RegisterType((*ServiceDescription)(nil), "registrar.ServiceDescription")
	proto.RegisterType((*ServiceAddress)(nil), "registrar.ServiceAddress")
	proto.RegisterType((*ServiceLocation)(nil), "registrar.ServiceLocation")
	proto.RegisterType((*GetRequest)(nil), "registrar.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "registrar.GetResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "registrar.ShutdownRequest")
	proto.RegisterType((*ListResponse)(nil), "registrar.ListResponse")
	proto.RegisterType((*EmptyResponse)(nil), "registrar.EmptyResponse")
	proto.RegisterType((*ListRequest)(nil), "registrar.ListRequest")
	proto.RegisterType((*DeregisterRequest)(nil), "registrar.DeregisterRequest")
	proto.RegisterEnum("registrar.ServiceDescription_Servicetype", ServiceDescription_Servicetype_name, ServiceDescription_Servicetype_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Registry service

type RegistryClient interface {
	DeregisterService(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	RegisterService(ctx context.Context, in *ServiceLocation, opts ...grpc.CallOption) (*GetResponse, error)
	GetServiceAddress(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	ListServices(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	ShutdownService(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type registryClient struct {
	cc *grpc.ClientConn
}

func NewRegistryClient(cc *grpc.ClientConn) RegistryClient {
	return &registryClient{cc}
}

func (c *registryClient) DeregisterService(ctx context.Context, in *DeregisterRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/registrar.Registry/DeregisterService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) RegisterService(ctx context.Context, in *ServiceLocation, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/registrar.Registry/RegisterService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) GetServiceAddress(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/registrar.Registry/GetServiceAddress", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ListServices(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := grpc.Invoke(ctx, "/registrar.Registry/ListServices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registryClient) ShutdownService(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := grpc.Invoke(ctx, "/registrar.Registry/ShutdownService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Registry service

type RegistryServer interface {
	DeregisterService(context.Context, *DeregisterRequest) (*EmptyResponse, error)
	RegisterService(context.Context, *ServiceLocation) (*GetResponse, error)
	GetServiceAddress(context.Context, *GetRequest) (*GetResponse, error)
	ListServices(context.Context, *ListRequest) (*ListResponse, error)
	ShutdownService(context.Context, *ShutdownRequest) (*EmptyResponse, error)
}

func RegisterRegistryServer(s *grpc.Server, srv RegistryServer) {
	s.RegisterService(&_Registry_serviceDesc, srv)
}

func _Registry_DeregisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).DeregisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registry/DeregisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).DeregisterService(ctx, req.(*DeregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_RegisterService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).RegisterService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registry/RegisterService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).RegisterService(ctx, req.(*ServiceLocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_GetServiceAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).GetServiceAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registry/GetServiceAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).GetServiceAddress(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registry/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ListServices(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registry_ShutdownService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServer).ShutdownService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/registrar.Registry/ShutdownService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServer).ShutdownService(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Registry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "registrar.Registry",
	HandlerType: (*RegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeregisterService",
			Handler:    _Registry_DeregisterService_Handler,
		},
		{
			MethodName: "RegisterService",
			Handler:    _Registry_RegisterService_Handler,
		},
		{
			MethodName: "GetServiceAddress",
			Handler:    _Registry_GetServiceAddress_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _Registry_ListServices_Handler,
		},
		{
			MethodName: "ShutdownService",
			Handler:    _Registry_ShutdownService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/registrar.proto",
}

func init() { proto.RegisterFile("proto/registrar.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 495 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x8e, 0xd2, 0x40,
	0x18, 0xb5, 0x50, 0x04, 0xbe, 0xea, 0xb2, 0x3b, 0x71, 0xb5, 0x36, 0x98, 0xd4, 0xb9, 0xc2, 0x9b,
	0x45, 0x4b, 0xa2, 0xde, 0x18, 0x75, 0x03, 0x41, 0xe3, 0xc6, 0x98, 0xd9, 0x27, 0xe8, 0xc2, 0x84,
	0xad, 0x81, 0x4e, 0x9d, 0x19, 0x34, 0x5c, 0xf9, 0x22, 0x5e, 0xf8, 0x80, 0x3e, 0x84, 0xe9, 0xfc,
	0x6c, 0x07, 0xba, 0xec, 0x05, 0x77, 0xed, 0x99, 0xef, 0x9c, 0x9e, 0x73, 0xe6, 0x03, 0x38, 0x2d,
	0x38, 0x93, 0x6c, 0xc8, 0xe9, 0x22, 0x13, 0x92, 0xa7, 0xfc, 0x4c, 0xbd, 0xa3, 0xee, 0x0d, 0x10,
	0xf5, 0x17, 0x8c, 0x2d, 0x96, 0x74, 0x98, 0x16, 0xd9, 0x30, 0xcd, 0x73, 0x26, 0x53, 0x99, 0xb1,
	0x5c, 0xe8, 0x41, 0xfc, 0xd7, 0x03, 0x74, 0x49, 0xf9, 0xcf, 0x6c, 0x46, 0xc7, 0x54, 0xcc, 0x78,
	0x56, 0x94, 0xa7, 0x08, 0x81, 0xff, 0x35, 0x5d, 0xd1, 0xd0, 0x8b, 0xbd, 0x41, 0x97, 0xf8, 0x79,
	0xba, 0xa2, 0xe8, 0x11, 0xb4, 0xce, 0xd7, 0xd9, 0x72, 0x1e, 0x36, 0x62, 0x6f, 0xd0, 0x24, 0xad,
	0xab, 0xf2, 0x05, 0xbd, 0x03, 0x5f, 0x6e, 0x0a, 0x1a, 0xfa, 0xb1, 0x37, 0x38, 0x4a, 0x5e, 0x9c,
	0x55, 0x4e, 0xea, 0xb2, 0x16, 0x2a, 0x09, 0x44, 0xd1, 0xf0, 0x73, 0x08, 0x1c, 0x10, 0x75, 0xc0,
	0x5f, 0xf0, 0x62, 0x76, 0x7c, 0xaf, 0x7c, 0xfa, 0x2e, 0x58, 0x7e, 0xec, 0xe1, 0xb7, 0x70, 0x64,
	0x46, 0x3e, 0xce, 0xe7, 0x9c, 0x0a, 0x51, 0xba, 0xfb, 0xc4, 0x84, 0xb4, 0xee, 0xae, 0x99, 0x90,
	0x25, 0xf6, 0x8d, 0x71, 0xa9, 0xcc, 0xb5, 0x88, 0x5f, 0x30, 0x2e, 0xf1, 0x6f, 0xe8, 0x19, 0xe6,
	0x05, 0x9b, 0xa9, 0xd8, 0xe8, 0x0d, 0xb4, 0x0d, 0xa4, 0xd8, 0x41, 0xf2, 0xec, 0x4e, 0xc7, 0xa4,
	0x2d, 0x34, 0x86, 0x46, 0xd0, 0x36, 0x9f, 0x0f, 0x1b, 0x71, 0x73, 0x10, 0x24, 0x4f, 0xeb, 0x44,
	0x33, 0x40, 0xda, 0xa9, 0x7e, 0xc0, 0x13, 0x80, 0x29, 0x95, 0x84, 0xfe, 0x58, 0x53, 0x21, 0x0f,
	0xfe, 0x36, 0xfe, 0xe3, 0x41, 0xa0, 0x74, 0x44, 0xc1, 0x72, 0x41, 0x0f, 0x0f, 0xf1, 0x1a, 0x3a,
	0xb6, 0x09, 0x55, 0x54, 0x90, 0x44, 0x75, 0xa6, 0x9d, 0x20, 0x9d, 0xa5, 0x6d, 0xad, 0x0f, 0x5d,
	0x73, 0xf8, 0x79, 0x1c, 0x36, 0x55, 0xeb, 0x5d, 0x61, 0x01, 0x3c, 0x82, 0xde, 0xe5, 0xf5, 0x5a,
	0xce, 0xd9, 0xaf, 0xdc, 0x46, 0x8d, 0x6f, 0xae, 0xd5, 0x59, 0xa3, 0x40, 0x54, 0x10, 0xfe, 0x00,
	0x0f, 0x2e, 0x32, 0x51, 0x65, 0x7a, 0x59, 0x65, 0x6a, 0xaa, 0x7e, 0x1f, 0x3b, 0xce, 0x9c, 0xf0,
	0x55, 0x2b, 0x3d, 0x78, 0x38, 0x59, 0x15, 0x72, 0x63, 0x4f, 0xca, 0x5d, 0xd2, 0x92, 0xda, 0xc3,
	0x2d, 0x3b, 0x8c, 0x5f, 0xc1, 0xc9, 0x98, 0x6a, 0x5d, 0xca, 0xed, 0xe0, 0x56, 0x3a, 0x6f, 0x27,
	0x5d, 0xf2, 0xaf, 0x01, 0x1d, 0xa2, 0x9d, 0x6c, 0xd0, 0x17, 0x97, 0x6f, 0x48, 0xa8, 0xef, 0x38,
	0xad, 0xa9, 0x47, 0xa1, 0x73, 0xba, 0xe5, 0x17, 0x4d, 0xa0, 0x47, 0x76, 0xa4, 0xee, 0xb8, 0x8e,
	0x68, 0x4f, 0x21, 0xe8, 0x1c, 0x4e, 0xa6, 0x54, 0xee, 0xfc, 0x44, 0x4e, 0x77, 0x87, 0xb5, 0x99,
	0x7d, 0x1a, 0xef, 0xf5, 0x6d, 0x18, 0x11, 0x81, 0xdc, 0x39, 0xa7, 0xd3, 0xe8, 0x49, 0x0d, 0x37,
	0x02, 0xd3, 0x6a, 0x07, 0x6e, 0xcd, 0xb2, 0xbd, 0x1f, 0xfb, 0x4b, 0xb9, 0xba, 0xaf, 0xfe, 0x97,
	0x46, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x0d, 0x01, 0x17, 0x7b, 0xd9, 0x04, 0x00, 0x00,
}
