// Code generated by protoc-gen-go.
// source: proto/auth.proto
// DO NOT EDIT!

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	proto/auth.proto

It has these top-level messages:
	VerifyRequest
	VerifyResponse
	GetDetailRequest
	GetDetailResponse
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//
// import "google/protobuf/empty.proto";
// import "google/protobuf/duration.proto";
// import "examples/sub/message.proto";
// import "examples/sub2/message.proto";
// import "google/protobuf/timestamp.proto";
type VerifyRequest struct {
	Token string `protobuf:"bytes,1,opt,name=Token,json=token" json:"Token,omitempty"`
}

func (m *VerifyRequest) Reset()                    { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()               {}
func (*VerifyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VerifyRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyResponse struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
}

func (m *VerifyResponse) Reset()                    { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string            { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()               {}
func (*VerifyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *VerifyResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetDetailRequest struct {
	UserID string `protobuf:"bytes,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
}

func (m *GetDetailRequest) Reset()                    { *m = GetDetailRequest{} }
func (m *GetDetailRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDetailRequest) ProtoMessage()               {}
func (*GetDetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetDetailRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetDetailResponse struct {
	UserID    string `protobuf:"bytes,1,opt,name=UserID,json=userID" json:"UserID,omitempty"`
	Email     string `protobuf:"bytes,2,opt,name=Email,json=email" json:"Email,omitempty"`
	Firstname string `protobuf:"bytes,3,opt,name=Firstname,json=firstname" json:"Firstname,omitempty"`
	Lastname  string `protobuf:"bytes,4,opt,name=Lastname,json=lastname" json:"Lastname,omitempty"`
}

func (m *GetDetailResponse) Reset()                    { *m = GetDetailResponse{} }
func (m *GetDetailResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDetailResponse) ProtoMessage()               {}
func (*GetDetailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetDetailResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDetailResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetDetailResponse) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *GetDetailResponse) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifyRequest)(nil), "auth.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "auth.VerifyResponse")
	proto.RegisterType((*GetDetailRequest)(nil), "auth.GetDetailRequest")
	proto.RegisterType((*GetDetailResponse)(nil), "auth.GetDetailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthenticationService service

type AuthenticationServiceClient interface {
	VerifyUserToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	GetUserDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error)
}

type authenticationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationServiceClient(cc *grpc.ClientConn) AuthenticationServiceClient {
	return &authenticationServiceClient{cc}
}

func (c *authenticationServiceClient) VerifyUserToken(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/VerifyUserToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationServiceClient) GetUserDetail(ctx context.Context, in *GetDetailRequest, opts ...grpc.CallOption) (*GetDetailResponse, error) {
	out := new(GetDetailResponse)
	err := grpc.Invoke(ctx, "/auth.AuthenticationService/GetUserDetail", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthenticationService service

type AuthenticationServiceServer interface {
	VerifyUserToken(context.Context, *VerifyRequest) (*VerifyResponse, error)
	GetUserDetail(context.Context, *GetDetailRequest) (*GetDetailResponse, error)
}

func RegisterAuthenticationServiceServer(s *grpc.Server, srv AuthenticationServiceServer) {
	s.RegisterService(&_AuthenticationService_serviceDesc, srv)
}

func _AuthenticationService_VerifyUserToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).VerifyUserToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/VerifyUserToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).VerifyUserToken(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthenticationService_GetUserDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServiceServer).GetUserDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthenticationService/GetUserDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServiceServer).GetUserDetail(ctx, req.(*GetDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthenticationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthenticationService",
	HandlerType: (*AuthenticationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyUserToken",
			Handler:    _AuthenticationService_VerifyUserToken_Handler,
		},
		{
			MethodName: "GetUserDetail",
			Handler:    _AuthenticationService_GetUserDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auth.proto",
}

func init() { proto.RegisterFile("proto/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0xb6, 0xa1, 0x19, 0xa8, 0xd6, 0xb1, 0xd6, 0x10, 0x7a, 0x90, 0x80, 0x50, 0x3c,
	0x34, 0xa0, 0x77, 0x41, 0xa9, 0x16, 0xc1, 0x53, 0xfd, 0x73, 0x5f, 0xcb, 0xb4, 0x5d, 0x4c, 0x77,
	0x63, 0x76, 0x22, 0x88, 0x1f, 0xc5, 0x2f, 0x2b, 0xbb, 0x9b, 0x80, 0x55, 0xf4, 0x36, 0x6f, 0xe6,
	0xb7, 0xc3, 0x9b, 0xb7, 0xd0, 0x2b, 0x4a, 0xcd, 0x3a, 0x13, 0x15, 0xaf, 0xc6, 0xae, 0xc4, 0x96,
	0xad, 0x93, 0xe1, 0x52, 0xeb, 0x65, 0x4e, 0x99, 0x28, 0x64, 0x26, 0x94, 0xd2, 0x2c, 0x58, 0x6a,
	0x65, 0x3c, 0x93, 0x9e, 0x40, 0xf7, 0x89, 0x4a, 0xb9, 0x78, 0x9f, 0xd1, 0x6b, 0x45, 0x86, 0xb1,
	0x0f, 0xed, 0x07, 0xfd, 0x42, 0x2a, 0x0e, 0x8e, 0x83, 0x51, 0x34, 0x6b, 0xb3, 0x15, 0xe9, 0x08,
	0x76, 0x1b, 0xcc, 0x14, 0x5a, 0x19, 0xc2, 0x01, 0x84, 0x8f, 0x86, 0xca, 0xdb, 0x49, 0x0d, 0x86,
	0x95, 0x53, 0xe9, 0x29, 0xf4, 0xa6, 0xc4, 0x13, 0x62, 0x21, 0xf3, 0x66, 0xe7, 0x5f, 0xec, 0x07,
	0xec, 0x7f, 0x63, 0xff, 0x5f, 0x6c, 0x8d, 0x5d, 0xaf, 0x85, 0xcc, 0xe3, 0x6d, 0x6f, 0x8c, 0xac,
	0xc0, 0x21, 0x44, 0x37, 0xb2, 0x34, 0xac, 0xc4, 0x9a, 0xe2, 0x1d, 0x37, 0x89, 0x16, 0x4d, 0x03,
	0x13, 0xe8, 0xdc, 0x89, 0x7a, 0xd8, 0x72, 0xc3, 0x4e, 0x5e, 0xeb, 0xb3, 0xcf, 0x00, 0x0e, 0x2f,
	0x2b, 0x5e, 0x91, 0x62, 0x39, 0x77, 0x99, 0xdc, 0x53, 0xf9, 0x26, 0xe7, 0x84, 0x17, 0xb0, 0xe7,
	0x8f, 0xb5, 0x3e, 0x5c, 0x18, 0x78, 0x30, 0x76, 0xb9, 0x6e, 0x44, 0x95, 0xf4, 0x37, 0x9b, 0xde,
	0x7f, 0xba, 0x85, 0x57, 0xd0, 0x9d, 0x12, 0xdb, 0xc7, 0xfe, 0x34, 0x1c, 0x78, 0xf0, 0x67, 0x2e,
	0xc9, 0xd1, 0xaf, 0x7e, 0xb3, 0xe3, 0x39, 0x74, 0xdf, 0x73, 0xfe, 0x15, 0x00, 0x00, 0xff, 0xff,
	0xfd, 0x84, 0xeb, 0x69, 0xd6, 0x01, 0x00, 0x00,
}
